// Open-loop drive: no sensors, no feedback. Runtime is derived from an
// empirically measured speed-vs-power curve. Distance accuracy depends
// entirely on that model holding (wheel slip, battery sag, etc. are
// unmodeled and uncorrected).
#pragma config(Motor,  port2,           motor1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           motor3,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(3000);

	motor[motor1] = 43;
	motor[motor2] = 43;
	motor[motor3] = 43;
	motor[motor4] = 43;

	float distance = 50; //inches
	float wheelDia = 2.75; //inches
	float wheelAngVelocity= (2*PI*90)/60; //rad/s, measured at power level 43 (~90 RPM)
	float runTime = (2*distance)/(wheelAngVelocity*wheelDia); //s, distance / linear wheel speed
	wait1Msec(runTime*1000);

}
