// Closed-loop drive, bang-bang control: full power until the target
// encoder count is reached, then hard stop. Removes the open-loop speed
// estimate in favor of measured position feedback, but has no
// deceleration profile.
#pragma config(Sensor, dgtl11, encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           motor3,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(4000);

	float distance = 50; //inches
	float wheelDia = 2.75; //inches
	float wheelCircum = wheelDia*PI; //inches
	float encoderTicks = (360/wheelCircum)*distance;  // Encoder ticks = (360 / circumference) * Distance to travel

	SensorValue[encoder] = 0;

	while(abs(SensorValue[encoder])<encoderTicks)

	{
		motor[motor1] = 63;
		motor[motor2] = 63;
		motor[motor3] = 63;
		motor[motor4] = 63;

	}
		motor[motor1] = 0;
		motor[motor2] = 0;
		motor[motor3] = 0;
		motor[motor4] = 0;
}
