// Closed-loop drive, proportional control: motor power scales with
// remaining distance (error = Xd - X), so the robot decelerates into the
// target instead of the hard stop in 02_closed_loop_bangbang_drive.c.
#pragma config(Sensor, dgtl11, encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           motor3,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(3000);

	float Xd = 50; //inches, target distance
	float wheelDia = 2.75; //inches
	float wheelCircum = wheelDia*PI; //inches
	float X=0; //inches, distance traveled so far
	//float maxWheelLinearVelocity= ((2*PI*90)/60)*(wheelDia/2); //wheel rpm is around 90 at power level 43

	SensorValue[encoder] = 0;

	// Encoder ticks = (360 / circumference) * Distance to travel

	while (abs(X/Xd)<=1)
	{
		X = (abs(SensorValue[encoder])*wheelCircum)/360;

		float velocity = 127*(1- X/Xd); // P control: velocity -> 0 as X -> Xd

		motor[motor1] = abs(velocity);
		motor[motor2] = abs(velocity);
		motor[motor3] = abs(velocity);
		motor[motor4] = abs(velocity);
	}
		motor[motor1] = 0;
		motor[motor2] = 0;
		motor[motor3] = 0;
		motor[motor4] = 0;
}
