// Closed-loop station-keeping, proportional control on sonar range: holds
// the robot at a fixed standoff distance from an object instead of driving
// a one-shot distance. Runs continuously, sampling at 10 Hz.
//
// Known limitation: motor power is always abs(speed), so the sign of the
// error is discarded and the robot can only drive forward, never reverse
// to back off if it gets closer than the target distance.
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_inch)
#pragma config(Sensor, dgtl11, encoder,        sensorQuadEncoder)
#pragma config(Motor,  port2,           motor1,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           motor3,        tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);
	int speed;            // Will hold a speed for the motors.
	int sonar_value;      // Will hold the current reading of the sonar sensor.
	int distance = 50;    // Specified distance to be at 50 inches.

	while(true)
	{
		sonar_value = SensorValue(sonarSensor);   // Store the current reading from the Sonar Sensor to 'sonar_value'.

		if(sonar_value < 0)                       // If the object is out of range: (returns -1)
		{
			speed = 30;
		}
		else
		{
		speed = (sonar_value - distance)*2;     // P control, Kp = 2: error = range - target
		//speed = 63*(sonar_value/distance);
		}
		motor[motor1] = abs(speed);
		motor[motor2] = abs(speed);
		motor[motor3] = abs(speed);
		motor[motor4] = abs(speed);                /* motors to run at 'speed'.   */

		wait1Msec(100);                           // Take 10 readings per second.
	}
}
